### ISSUE TITLE
RuntimeError: not found?

### ISSUE THREAD

**Issue by EddieOne** [phrase/phraseapp-in-context-editor-ruby#12]
We installed the in-context editor on one site without issue. On the other, I keep getting this not found error and it's not clear what is the cause. Is anyone familiar with the not found error?

```
irb(main):001:0> I18n.t('test', default: 'test')
RuntimeError: not found
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-ruby-1.2.7/lib/phraseapp-ruby/request_handler.rb:157:in `handleResponseStatus'
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-ruby-1.2.7/lib/phraseapp-ruby/request_handler.rb:145:in `http_send'
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-ruby-1.2.7/lib/phraseapp-ruby/request_handler.rb:103:in `send_request'
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-ruby-1.2.7/lib/phraseapp-ruby/request_handler.rb:80:in `send_request_paginated'
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-ruby-1.2.7/lib/phraseapp-ruby.rb:2007:in `blacklisted_keys_list'
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-in-context-editor-ruby-1.0.5/lib/phraseapp-in-context-editor-ruby/api_collection.rb:36:in `send_request'
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-in-context-editor-ruby-1.0.5/lib/phraseapp-in-context-editor-ruby/api_collection.rb:17:in `collection'
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-in-context-editor-ruby-1.0.5/lib/phraseapp-in-context-editor-ruby/api_wrapper.rb:38:in `blacklisted_keys'
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-in-context-editor-ruby-1.0.5/lib/phraseapp-in-context-editor-ruby/backend_service.rb:61:in `blacklisted_keys'
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-in-context-editor-ruby-1.0.5/lib/phraseapp-in-context-editor-ruby/backend_service.rb:47:in `has_blacklist_entry_for_key?'
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-in-context-editor-ruby-1.0.5/lib/phraseapp-in-context-editor-ruby/backend_service.rb:30:in `has_been_given_blacklisted_key?'
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-in-context-editor-ruby-1.0.5/lib/phraseapp-in-context-editor-ruby/backend_service.rb:25:in `to_be_translated_without_phraseapp?'
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-in-context-editor-ruby-1.0.5/lib/phraseapp-in-context-editor-ruby/backend_service.rb:16:in `translate'
    from /shared/bundle/ruby/2.1.0/gems/phraseapp-in-context-editor-ruby-1.0.5/lib/phraseapp-in-context-editor-ruby/adapters/i18n.rb:6:in `translate_with_phraseapp'
    from (irb):1
```

**Comment by docstun** [comment]
This looks like a configuration issue. Are you sure you entered the correct project id? And does the access token in your initializer belong to a user that has access to that project?

**Comment by EddieOne** [comment]
Ah you're right. The project id was not correct. Thank you

**Comment by docstun** [comment]
Glad I could help!
